### ISSUE TITLE
Just tried your package 

### ISSUE THREAD

**Issue by gracecompany** [QuincePHP/AutoProvider#3]
got this error 

```
ErrorException in AutoProvider.php line 157:
in_array() expects parameter 2 to be array, null given
```

What you package needs to do is scan vendors for all files ending in Provider.php and add them to the 'providers' array in config/app.php

**Comment by behzadsh** [comment]
@gracecompany This is an abandoned package, and no longer maintained.

What you asked for would decrease performance when there are many packages that have service provider.
